### ISSUE TITLE
Swiper goes back to previous card every time setState() is called

### ISSUE THREAD

**Issue by zelgan90** [alexbrillant/react-native-deck-swiper#115]
There's already a closed issue for this, I don't know why since this issue is still present in the component, every time a modal shows up in the screen the cards reset for some reason.

EDIT: it doesn't reset, it just goes back to the previous card.

EDIT 2: it happens every time a setState() is called.

**Comment by zelgan90** [comment]
This is solved in version 1.4.8

**Comment by QQizi** [comment]
I still have this issue. When i setState (any state) in my parent component, the Swiper child component just reset the active card to the index 0

**Comment by zelgan90** [comment]
Are you sure you are usimg the latest version of this module?

**Comment by zelgan90** [comment]
@QQizi Did you solve it?

**Comment by QQizi** [comment]
I used a work around, i just set a state in my component which save the current index and use this index as initial cardIndex.
So even if it reset, it reset at the actual index.
(Had to move on an other project so i couldn't debug further)

**Comment by simdonl** [comment]
@QQizi Solution works on iOS, but unfortunately not on Android.

**Comment by collaorodrigo7** [comment]
I am having the same issue. But luckily @QQizi  workaround work for Android and iOS for me.

**Comment by webraptor** [comment]
@zelgan90 @QQizi @simdonl @collaorodrigo7 
This is the intended behaviour. Whenever the swiper receives new props, the card indexes are computed. If the first card index is not available it is set to 0 (the 1st card).

Therefor, if you keep state in a parent component that contains the swiper, and you modify the state, the swiper will get a _componentWillReceiveProps_ event which will reset the cardIndex.

There's two solutions for this:
1. The one mentioned by @QQizi [above](https://github.com/alexbrillant/react-native-deck-swiper/issues/115#issuecomment-395245806)
2. Make sure that the swiper doesn't receive new props after the initial render (but this is almost impossible in a real application scenario).

PS: even when we switch from _componentWillReceiveProps_ to _getDerivedStateFromProps_ the same logic and flow will happen.
