### ISSUE TITLE
Flickering with image content

### ISSUE THREAD

**Issue by alexbrillant** [alexbrillant/react-native-deck-swiper#12]

**Comment by keyclipse** [comment]
I have the same problem here.. It flickers after the swiping animation ended

**Comment by mu29** [comment]
same problem here

**Comment by novakben** [comment]
Same here!

**Comment by ttoti** [comment]
@mu29 Thanks for the work around

**Comment by novakben** [comment]
@mu29 works for me aswell. Awesome.

**Comment by lsps9150414** [comment]
@mu29 Do you known why `react-native-fast-image` solve it for you? I'm trying to understand what caused the flickering, RN's `Image`'s problem or `react-native-deck-swiper`'s.

**Comment by alexbrillant** [comment]
@mu29 I added your workaround to the README thanks alot ! Do you think I should close this issue or leave it opened ?

**Comment by mu29** [comment]
@alexbrillant I think we shoud keep this issue opened :)

**Comment by alexbrillant** [comment]
@mu29  alright I'll keep it opened. It is also related to the fact that I reuse the card Views...

**Comment by mu29** [comment]
@lsps9150414 alexbrillant's answer may help you

**Comment by WaqqaR** [comment]
this might be a noobish question , but how do I put images or other content in the tiles? the card data array from the example is simply:
cards: ["1", "2", "3", "4", "5", "6", "7"]

**Comment by designorant** [comment]
@WaqqaR Could you please ask that on StackOverflow? Feel free to send me the URL (@designorant on most social media) for a swift answer. Let's keep the issue log clean.

**Comment by rmanniez** [comment]
Hello i just add unique key from card on view (renderFirstCard, renderSecondCard, renderSwipeBackCard).

Swiper.js  :
 ```
 renderFirstCard = () => {
    const { firstCardIndex } = this.state
    const { cards } = this.props

    const swipableCardStyle = this.calculateSwipableCardStyle()
    const firstCardContent = cards[firstCardIndex]
    const firstCard = this.props.renderCard(firstCardContent)
    const renderOverlayLabel = this.renderOverlayLabel()

    const notInfinite = !this.props.infinite
    if (notInfinite && this.state.swipedAllCards) {
      return <Animated.View />
    }

    return (
      <Animated.View
        style={swipableCardStyle}
        key={firstCardContent.product__id}
        {...this._panResponder.panHandlers}
      >
        {renderOverlayLabel}
        {firstCard}
      </Animated.View>
    )
  }

  renderSecondCard = () => {
    const { secondCardIndex } = this.state
    const { cards, renderCard, showSecondCard } = this.props

    const secondCardZoomStyle = this.calculateSecondCardZoomStyle()
    const secondCardContent = cards[secondCardIndex]
    const secondCard = renderCard(secondCardContent)

    const notInfinite = !this.props.infinite
    const lastCardOrSwipedAllCards =
      secondCardIndex === 0 || this.state.swipedAllCards
    if (notInfinite && lastCardOrSwipedAllCards) {
      return <Animated.View />
    }

    return (
      <Animated.View key={secondCardContent.product__id} style={secondCardZoomStyle}>
        {showSecondCard ? secondCard : null}
      </Animated.View>
    )
  }

  renderSwipeBackCard = () => {
    const { previousCardIndex } = this.state
    const { cards } = this.props
    const previousCardContent = cards[previousCardIndex]
    const previousCardStyle = this.calculateSwipeBackCardStyle()
    const previousCard = this.props.renderCard(previousCardContent)
    return (
      <Animated.View key={previousCardContent.product__id} style={previousCardStyle}>
        {previousCard}
      </Animated.View>
    )
  }

```
Work for you ?

**Comment by alexbrillant** [comment]
@rmanniez  you nailed it ! it works like a charm thanks alot  👍  💯

**Comment by alexbrillant** [comment]
adding a unique key prop to the cards did the trick ! I used the firstCardIndex, secondCardIndex, and previousCardIndex for the keys.

**Comment by alexbrillant** [comment]
fixed in 1.3.7 !

**Comment by mu29** [comment]
Awesome :)

**Comment by lsps9150414** [comment]
I'm still seeing the flickering after upgrading to 1.3.7

![9 -18-2017 11-38-36](https://user-images.githubusercontent.com/5022617/30528476-fd56e454-9c65-11e7-9bbc-38cc487adc4a.gif)

I'm using Expo on a simulator with debug JS remotely turned off.

**Comment by alexbrillant** [comment]
@lsps9150414  This would be a different issue. It doesn't flash the **previous image** like it did before in  1.3.7. It flashes because the new image is fetched twice. The first card resets when the animation is done(second card has the same image before the first card resets).

**Comment by lsps9150414** [comment]
@alexbrillant I also found that the issue only happens on iOS not Android. So seems this is a performance issue with the `Image` component on the iOS platform?

**Comment by rmanniez** [comment]
You use preloading and cache assets by Expo ? https://docs.expo.io/versions/latest/guides/preloading-and-caching-assets.html

**Comment by alexbrillant** [comment]
@lsps9150414 Maybe, I don't know. Tell me if you find anything. I need to avoid changing the top view when the animation is done, but I don't know how yet.

**Comment by lsps9150414** [comment]
@rmanniez Yes I did. It happens even with local images.

**Comment by lsps9150414** [comment]
@alexbrillant Not changing the top view sounds like a good path to fix this. Is it possible to interchange `renderFirstCard` and `renderSecondCard`'s `z-index`?

**Comment by lsps9150414** [comment]
@alexbrillant I believe, as @rmanniez suggested, it can be fix by adding `secondCardIndex` as the key to `renderSecoundCard` so that react knows to reuse the card component instead of creating a new one:  https://github.com/alexbrillant/react-native-deck-swiper/blob/master/Swiper.js#L696

I see you only add the `key` to renderFirstCard`.

**Comment by rmanniez** [comment]
I have the same problem, I tried to solve it but impossible to find a solution and the exact reason.
Unable to get into production with this problem :/

**Comment by rmanniez** [comment]
@lsps9150414 i found the problem :

Try to remove {renderOverlayLabel} on renderFirstCard(), i don't use overlay and work for me.

Good for you too ?

**Comment by jalieven** [comment]
@alexbrillant maybe you could conditionally not render the renderOverlayLabel inside the renderFirstCard when there is no overlayLabel?

**Comment by webraptor** [comment]
I think this issue should be reopened as it still occurs under different circumstances (including with or without overlay labels). I've been doing some thorough tests within the past hour or so and, although it doesn't happen on each swipe), it still happens to roughly 60% of swipes (I've even tested with decks ranging 100+ cards).

It is clear that this has to do with rendering performance (deck size, image size etc) and also it shouldn't be acceptable to just say thing like just don't use feature X of the package ...

**Comment by webraptor** [comment]
My idea is that flickering occurs due to the swipe animation, under the following steps:
1. Swipe in any direction is performed
2. Animation is triggered to move the card out of view
3. Top card is placed on top of the deck
4. Content changes (second card -> first card, then new content on second card)

Sometimes it doesn't flicker because steps 3 and 4 happen so quickly that we cannot actually see that with the human eye (this happens when processing is blazing fast).
Sometimes it flickers because processing isn't fast enough and there's some lag between steps 3 and 4.

One solution would be to set opacity of 1st card to 0 when animation finishes, move it back on top, load content, then set opacity back to 1. This way, should processing be slow, we will not be able to see any flickering.

**Comment by rmanniez** [comment]
@jalieven You have to try to include in the renderCard I think. I will try when I have a time.

**Comment by webraptor** [comment]
Further testing revealed the issue. Sometimes, while swiping (not at 1st swipe) the following happens:
1. First card (1) rendered; Second card (2) rendered beneath;
2. Swipe happens
3. First card (1) rendered; Second card (OLD-ID; from an older swipe) is rendered;
4. Second card (2) is rendered at First card; Second card (OLD-ID; from an older swipe) is rendered as second card;
5. Second card (2) is rendered at First card; New card (NEW) is rendered as second card.

(X) denotes card unique IDs based on card properties
Steps 3, 4 and 5 happen blazingly fast.

**Comment by webraptor** [comment]
Also done some video recordings and can confirm that a brief blank image area is displayed.

**Comment by gonzaloriestra** [comment]
If you are using static images, the problem can be solved by using the [defaultSource prop from Image component](https://facebook.github.io/react-native/docs/image#defaultsource), as it is suggested here: https://github.com/facebook/react-native/issues/981#issuecomment-354767548
